# Generated by Django 4.2.7 on 2025-10-28 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierperformancereports',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ordered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='moved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.DeleteModel(
            name='SupplierPayment',
        ),
        migrations.DeleteModel(
            name='SupplierPerformanceReports',
        ),
    ]
