# Generated by Django 4.2.7 on 2025-10-28 15:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('suppliers', '0002_remove_supplierperformancereports_supplier_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateField(db_index=True, unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_customers', models.IntegerField(default=0)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('mpesa_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('card_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_sales_summary',
                'ordering': ['-summary_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpiryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, unique=True)),
                ('expired_items', models.IntegerField(default=0)),
                ('expired_items_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expiring_this_month', models.IntegerField(default=0)),
                ('expiring_this_month_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expiring_next_month', models.IntegerField(default=0)),
                ('expiring_next_month_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expired_items_list', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'expiry_reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, unique=True)),
                ('total_products', models.IntegerField(default=0)),
                ('total_stock_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('low_stock_items', models.IntegerField(default=0)),
                ('expiring_soon_items', models.IntegerField(default=0)),
                ('out_of_stock_items', models.IntegerField(default=0)),
                ('fast_moving_products', models.JSONField(blank=True, null=True)),
                ('slow_moving_products', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_date', models.DateField(db_index=True, unique=True)),
                ('total_quantity', models.IntegerField(default=0)),
                ('total_cost_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_retail_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_valuations',
                'ordering': ['-valuation_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_amount_purchased', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('on_time_deliveries', models.IntegerField(default=0)),
                ('late_deliveries', models.IntegerField(default=0)),
                ('average_delivery_time', models.IntegerField(default=0)),
                ('quality_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_performance', to='suppliers.supplier')),
            ],
            options={
                'db_table': 'supplier_performance_reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='ProfitabilityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=50)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profitability_reports',
                'ordering': ['-report_date'],
                'unique_together': {('report_date', 'period_type')},
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=50)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('accounts_receivable_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('accounts_payable_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cash_flow', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'financial_reports',
                'ordering': ['-report_date'],
                'unique_together': {('report_date', 'period_type')},
            },
        ),
        migrations.CreateModel(
            name='CustomerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=50)),
                ('total_customers', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('returning_customers', models.IntegerField(default=0)),
                ('total_loyalty_points_issued', models.IntegerField(default=0)),
                ('average_customer_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('top_customers', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer_reports',
                'ordering': ['-report_date'],
                'unique_together': {('report_date', 'period_type')},
            },
        ),
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
                ('favorite_category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='customers.customer')),
            ],
            options={
                'db_table': 'customer_analytics',
            },
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=50)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('average_transaction_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('top_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_top_customer', to='customers.customer')),
                ('top_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_top_product', to='products.product')),
            ],
            options={
                'db_table': 'sales_reports',
                'ordering': ['-report_date'],
                'unique_together': {('report_date', 'period_type')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=50)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_items_purchased', models.IntegerField(default=0)),
                ('total_suppliers', models.IntegerField(default=0)),
                ('average_purchase_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('top_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_top_supplier', to='suppliers.supplier')),
            ],
            options={
                'db_table': 'purchase_reports',
                'ordering': ['-report_date'],
                'unique_together': {('report_date', 'period_type')},
            },
        ),
    ]
